//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.261
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace HotelAddInApp.dirs21 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DIRS21 PMS-InterfaceSoap", Namespace="http://www.dirs21.de/")]
    public partial class DIRS21PMSInterface : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadActiveRoomtypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadAvailabilitiesPricesMinstayOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadBookingAddOnsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadBookingdetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadBookingdetailsMergedOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadBookingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadBookingsPMSValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadBookingsPMSValueAndStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadInactiveRoomtypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadNotificationFaxnumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteAvailabilitiesPricesMinstayOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteAvailabilitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteVaryingAvailabilitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteBookingFlagOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteMinstayOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteVaryingMinStaysOperationCompleted;
        
        private System.Threading.SendOrPostCallback WritePricesOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteVaryingPricesOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteVaryingAvailabilitiesMinStaysPricesOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteDefinedAvailabilitiesMinStaysPricesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DIRS21PMSInterface() {
            this.Url = global::HotelAddInApp.Properties.Settings.Default.HotelAddInApp_dirs21_DIRS21_x0020_PMS_Interface;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadActiveRoomtypesCompletedEventHandler ReadActiveRoomtypesCompleted;
        
        /// <remarks/>
        public event ReadAvailabilitiesPricesMinstayCompletedEventHandler ReadAvailabilitiesPricesMinstayCompleted;
        
        /// <remarks/>
        public event ReadBookingAddOnsCompletedEventHandler ReadBookingAddOnsCompleted;
        
        /// <remarks/>
        public event ReadBookingdetailsCompletedEventHandler ReadBookingdetailsCompleted;
        
        /// <remarks/>
        public event ReadBookingdetailsMergedCompletedEventHandler ReadBookingdetailsMergedCompleted;
        
        /// <remarks/>
        public event ReadBookingsCompletedEventHandler ReadBookingsCompleted;
        
        /// <remarks/>
        public event ReadBookingsPMSValueCompletedEventHandler ReadBookingsPMSValueCompleted;
        
        /// <remarks/>
        public event ReadBookingsPMSValueAndStatusCompletedEventHandler ReadBookingsPMSValueAndStatusCompleted;
        
        /// <remarks/>
        public event ReadInactiveRoomtypesCompletedEventHandler ReadInactiveRoomtypesCompleted;
        
        /// <remarks/>
        public event ReadNotificationFaxnumberCompletedEventHandler ReadNotificationFaxnumberCompleted;
        
        /// <remarks/>
        public event WriteAvailabilitiesPricesMinstayCompletedEventHandler WriteAvailabilitiesPricesMinstayCompleted;
        
        /// <remarks/>
        public event WriteAvailabilitiesCompletedEventHandler WriteAvailabilitiesCompleted;
        
        /// <remarks/>
        public event WriteVaryingAvailabilitiesCompletedEventHandler WriteVaryingAvailabilitiesCompleted;
        
        /// <remarks/>
        public event WriteBookingFlagCompletedEventHandler WriteBookingFlagCompleted;
        
        /// <remarks/>
        public event WriteMinstayCompletedEventHandler WriteMinstayCompleted;
        
        /// <remarks/>
        public event WriteVaryingMinStaysCompletedEventHandler WriteVaryingMinStaysCompleted;
        
        /// <remarks/>
        public event WritePricesCompletedEventHandler WritePricesCompleted;
        
        /// <remarks/>
        public event WriteVaryingPricesCompletedEventHandler WriteVaryingPricesCompleted;
        
        /// <remarks/>
        public event WriteVaryingAvailabilitiesMinStaysPricesCompletedEventHandler WriteVaryingAvailabilitiesMinStaysPricesCompleted;
        
        /// <remarks/>
        public event WriteDefinedAvailabilitiesMinStaysPricesCompletedEventHandler WriteDefinedAvailabilitiesMinStaysPricesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/ReadActiveRoomtypes", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReadActiveRoomtypes(int knr, string pwd) {
            object[] results = this.Invoke("ReadActiveRoomtypes", new object[] {
                        knr,
                        pwd});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReadActiveRoomtypesAsync(int knr, string pwd) {
            this.ReadActiveRoomtypesAsync(knr, pwd, null);
        }
        
        /// <remarks/>
        public void ReadActiveRoomtypesAsync(int knr, string pwd, object userState) {
            if ((this.ReadActiveRoomtypesOperationCompleted == null)) {
                this.ReadActiveRoomtypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadActiveRoomtypesOperationCompleted);
            }
            this.InvokeAsync("ReadActiveRoomtypes", new object[] {
                        knr,
                        pwd}, this.ReadActiveRoomtypesOperationCompleted, userState);
        }
        
        private void OnReadActiveRoomtypesOperationCompleted(object arg) {
            if ((this.ReadActiveRoomtypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadActiveRoomtypesCompleted(this, new ReadActiveRoomtypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/ReadAvailabilitiesPricesMinstay", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReadAvailabilitiesPricesMinstay(int knr, string pwd, int ztyp, string sdatum, string edatum) {
            object[] results = this.Invoke("ReadAvailabilitiesPricesMinstay", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        edatum});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAvailabilitiesPricesMinstayAsync(int knr, string pwd, int ztyp, string sdatum, string edatum) {
            this.ReadAvailabilitiesPricesMinstayAsync(knr, pwd, ztyp, sdatum, edatum, null);
        }
        
        /// <remarks/>
        public void ReadAvailabilitiesPricesMinstayAsync(int knr, string pwd, int ztyp, string sdatum, string edatum, object userState) {
            if ((this.ReadAvailabilitiesPricesMinstayOperationCompleted == null)) {
                this.ReadAvailabilitiesPricesMinstayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadAvailabilitiesPricesMinstayOperationCompleted);
            }
            this.InvokeAsync("ReadAvailabilitiesPricesMinstay", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        edatum}, this.ReadAvailabilitiesPricesMinstayOperationCompleted, userState);
        }
        
        private void OnReadAvailabilitiesPricesMinstayOperationCompleted(object arg) {
            if ((this.ReadAvailabilitiesPricesMinstayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadAvailabilitiesPricesMinstayCompleted(this, new ReadAvailabilitiesPricesMinstayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/ReadBookingAddOns", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReadBookingAddOns(int knr, string pwd, int bid) {
            object[] results = this.Invoke("ReadBookingAddOns", new object[] {
                        knr,
                        pwd,
                        bid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReadBookingAddOnsAsync(int knr, string pwd, int bid) {
            this.ReadBookingAddOnsAsync(knr, pwd, bid, null);
        }
        
        /// <remarks/>
        public void ReadBookingAddOnsAsync(int knr, string pwd, int bid, object userState) {
            if ((this.ReadBookingAddOnsOperationCompleted == null)) {
                this.ReadBookingAddOnsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadBookingAddOnsOperationCompleted);
            }
            this.InvokeAsync("ReadBookingAddOns", new object[] {
                        knr,
                        pwd,
                        bid}, this.ReadBookingAddOnsOperationCompleted, userState);
        }
        
        private void OnReadBookingAddOnsOperationCompleted(object arg) {
            if ((this.ReadBookingAddOnsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadBookingAddOnsCompleted(this, new ReadBookingAddOnsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/ReadBookingdetails", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReadBookingdetails(int knr, string pwd, int bid) {
            object[] results = this.Invoke("ReadBookingdetails", new object[] {
                        knr,
                        pwd,
                        bid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReadBookingdetailsAsync(int knr, string pwd, int bid) {
            this.ReadBookingdetailsAsync(knr, pwd, bid, null);
        }
        
        /// <remarks/>
        public void ReadBookingdetailsAsync(int knr, string pwd, int bid, object userState) {
            if ((this.ReadBookingdetailsOperationCompleted == null)) {
                this.ReadBookingdetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadBookingdetailsOperationCompleted);
            }
            this.InvokeAsync("ReadBookingdetails", new object[] {
                        knr,
                        pwd,
                        bid}, this.ReadBookingdetailsOperationCompleted, userState);
        }
        
        private void OnReadBookingdetailsOperationCompleted(object arg) {
            if ((this.ReadBookingdetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadBookingdetailsCompleted(this, new ReadBookingdetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/ReadBookingdetailsMerged", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReadBookingdetailsMerged(int knr, string pwd, int bid) {
            object[] results = this.Invoke("ReadBookingdetailsMerged", new object[] {
                        knr,
                        pwd,
                        bid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReadBookingdetailsMergedAsync(int knr, string pwd, int bid) {
            this.ReadBookingdetailsMergedAsync(knr, pwd, bid, null);
        }
        
        /// <remarks/>
        public void ReadBookingdetailsMergedAsync(int knr, string pwd, int bid, object userState) {
            if ((this.ReadBookingdetailsMergedOperationCompleted == null)) {
                this.ReadBookingdetailsMergedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadBookingdetailsMergedOperationCompleted);
            }
            this.InvokeAsync("ReadBookingdetailsMerged", new object[] {
                        knr,
                        pwd,
                        bid}, this.ReadBookingdetailsMergedOperationCompleted, userState);
        }
        
        private void OnReadBookingdetailsMergedOperationCompleted(object arg) {
            if ((this.ReadBookingdetailsMergedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadBookingdetailsMergedCompleted(this, new ReadBookingdetailsMergedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/ReadBookings", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReadBookings(int knr, string pwd, string sdatum, string edatum) {
            object[] results = this.Invoke("ReadBookings", new object[] {
                        knr,
                        pwd,
                        sdatum,
                        edatum});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReadBookingsAsync(int knr, string pwd, string sdatum, string edatum) {
            this.ReadBookingsAsync(knr, pwd, sdatum, edatum, null);
        }
        
        /// <remarks/>
        public void ReadBookingsAsync(int knr, string pwd, string sdatum, string edatum, object userState) {
            if ((this.ReadBookingsOperationCompleted == null)) {
                this.ReadBookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadBookingsOperationCompleted);
            }
            this.InvokeAsync("ReadBookings", new object[] {
                        knr,
                        pwd,
                        sdatum,
                        edatum}, this.ReadBookingsOperationCompleted, userState);
        }
        
        private void OnReadBookingsOperationCompleted(object arg) {
            if ((this.ReadBookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadBookingsCompleted(this, new ReadBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/ReadBookingsPMSValue", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReadBookingsPMSValue(int knr, string pwd, int pmsvalue) {
            object[] results = this.Invoke("ReadBookingsPMSValue", new object[] {
                        knr,
                        pwd,
                        pmsvalue});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReadBookingsPMSValueAsync(int knr, string pwd, int pmsvalue) {
            this.ReadBookingsPMSValueAsync(knr, pwd, pmsvalue, null);
        }
        
        /// <remarks/>
        public void ReadBookingsPMSValueAsync(int knr, string pwd, int pmsvalue, object userState) {
            if ((this.ReadBookingsPMSValueOperationCompleted == null)) {
                this.ReadBookingsPMSValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadBookingsPMSValueOperationCompleted);
            }
            this.InvokeAsync("ReadBookingsPMSValue", new object[] {
                        knr,
                        pwd,
                        pmsvalue}, this.ReadBookingsPMSValueOperationCompleted, userState);
        }
        
        private void OnReadBookingsPMSValueOperationCompleted(object arg) {
            if ((this.ReadBookingsPMSValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadBookingsPMSValueCompleted(this, new ReadBookingsPMSValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/ReadBookingsPMSValueAndStatus", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReadBookingsPMSValueAndStatus(int knr, string pwd, int pmsvalue, int status) {
            object[] results = this.Invoke("ReadBookingsPMSValueAndStatus", new object[] {
                        knr,
                        pwd,
                        pmsvalue,
                        status});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReadBookingsPMSValueAndStatusAsync(int knr, string pwd, int pmsvalue, int status) {
            this.ReadBookingsPMSValueAndStatusAsync(knr, pwd, pmsvalue, status, null);
        }
        
        /// <remarks/>
        public void ReadBookingsPMSValueAndStatusAsync(int knr, string pwd, int pmsvalue, int status, object userState) {
            if ((this.ReadBookingsPMSValueAndStatusOperationCompleted == null)) {
                this.ReadBookingsPMSValueAndStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadBookingsPMSValueAndStatusOperationCompleted);
            }
            this.InvokeAsync("ReadBookingsPMSValueAndStatus", new object[] {
                        knr,
                        pwd,
                        pmsvalue,
                        status}, this.ReadBookingsPMSValueAndStatusOperationCompleted, userState);
        }
        
        private void OnReadBookingsPMSValueAndStatusOperationCompleted(object arg) {
            if ((this.ReadBookingsPMSValueAndStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadBookingsPMSValueAndStatusCompleted(this, new ReadBookingsPMSValueAndStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/ReadInactiveRoomtypes", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReadInactiveRoomtypes(int knr, string pwd) {
            object[] results = this.Invoke("ReadInactiveRoomtypes", new object[] {
                        knr,
                        pwd});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReadInactiveRoomtypesAsync(int knr, string pwd) {
            this.ReadInactiveRoomtypesAsync(knr, pwd, null);
        }
        
        /// <remarks/>
        public void ReadInactiveRoomtypesAsync(int knr, string pwd, object userState) {
            if ((this.ReadInactiveRoomtypesOperationCompleted == null)) {
                this.ReadInactiveRoomtypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadInactiveRoomtypesOperationCompleted);
            }
            this.InvokeAsync("ReadInactiveRoomtypes", new object[] {
                        knr,
                        pwd}, this.ReadInactiveRoomtypesOperationCompleted, userState);
        }
        
        private void OnReadInactiveRoomtypesOperationCompleted(object arg) {
            if ((this.ReadInactiveRoomtypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadInactiveRoomtypesCompleted(this, new ReadInactiveRoomtypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/ReadNotificationFaxnumber", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReadNotificationFaxnumber(int knr, string pwd) {
            object[] results = this.Invoke("ReadNotificationFaxnumber", new object[] {
                        knr,
                        pwd});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReadNotificationFaxnumberAsync(int knr, string pwd) {
            this.ReadNotificationFaxnumberAsync(knr, pwd, null);
        }
        
        /// <remarks/>
        public void ReadNotificationFaxnumberAsync(int knr, string pwd, object userState) {
            if ((this.ReadNotificationFaxnumberOperationCompleted == null)) {
                this.ReadNotificationFaxnumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadNotificationFaxnumberOperationCompleted);
            }
            this.InvokeAsync("ReadNotificationFaxnumber", new object[] {
                        knr,
                        pwd}, this.ReadNotificationFaxnumberOperationCompleted, userState);
        }
        
        private void OnReadNotificationFaxnumberOperationCompleted(object arg) {
            if ((this.ReadNotificationFaxnumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadNotificationFaxnumberCompleted(this, new ReadNotificationFaxnumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/WriteAvailabilitiesPricesMinstay", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteAvailabilitiesPricesMinstay(int knr, string pwd, int ztyp, string sdatum, string edatum, int availability, float price, int minstay) {
            object[] results = this.Invoke("WriteAvailabilitiesPricesMinstay", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        edatum,
                        availability,
                        price,
                        minstay});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteAvailabilitiesPricesMinstayAsync(int knr, string pwd, int ztyp, string sdatum, string edatum, int availability, float price, int minstay) {
            this.WriteAvailabilitiesPricesMinstayAsync(knr, pwd, ztyp, sdatum, edatum, availability, price, minstay, null);
        }
        
        /// <remarks/>
        public void WriteAvailabilitiesPricesMinstayAsync(int knr, string pwd, int ztyp, string sdatum, string edatum, int availability, float price, int minstay, object userState) {
            if ((this.WriteAvailabilitiesPricesMinstayOperationCompleted == null)) {
                this.WriteAvailabilitiesPricesMinstayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteAvailabilitiesPricesMinstayOperationCompleted);
            }
            this.InvokeAsync("WriteAvailabilitiesPricesMinstay", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        edatum,
                        availability,
                        price,
                        minstay}, this.WriteAvailabilitiesPricesMinstayOperationCompleted, userState);
        }
        
        private void OnWriteAvailabilitiesPricesMinstayOperationCompleted(object arg) {
            if ((this.WriteAvailabilitiesPricesMinstayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteAvailabilitiesPricesMinstayCompleted(this, new WriteAvailabilitiesPricesMinstayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/WriteAvailabilities", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteAvailabilities(int knr, string pwd, int ztyp, string sdatum, string edatum, int availability) {
            object[] results = this.Invoke("WriteAvailabilities", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        edatum,
                        availability});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteAvailabilitiesAsync(int knr, string pwd, int ztyp, string sdatum, string edatum, int availability) {
            this.WriteAvailabilitiesAsync(knr, pwd, ztyp, sdatum, edatum, availability, null);
        }
        
        /// <remarks/>
        public void WriteAvailabilitiesAsync(int knr, string pwd, int ztyp, string sdatum, string edatum, int availability, object userState) {
            if ((this.WriteAvailabilitiesOperationCompleted == null)) {
                this.WriteAvailabilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteAvailabilitiesOperationCompleted);
            }
            this.InvokeAsync("WriteAvailabilities", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        edatum,
                        availability}, this.WriteAvailabilitiesOperationCompleted, userState);
        }
        
        private void OnWriteAvailabilitiesOperationCompleted(object arg) {
            if ((this.WriteAvailabilitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteAvailabilitiesCompleted(this, new WriteAvailabilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/WriteVaryingAvailabilities", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteVaryingAvailabilities(int knr, string pwd, int ztyp, string sdatum, int[] vakanzen) {
            object[] results = this.Invoke("WriteVaryingAvailabilities", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        vakanzen});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteVaryingAvailabilitiesAsync(int knr, string pwd, int ztyp, string sdatum, int[] vakanzen) {
            this.WriteVaryingAvailabilitiesAsync(knr, pwd, ztyp, sdatum, vakanzen, null);
        }
        
        /// <remarks/>
        public void WriteVaryingAvailabilitiesAsync(int knr, string pwd, int ztyp, string sdatum, int[] vakanzen, object userState) {
            if ((this.WriteVaryingAvailabilitiesOperationCompleted == null)) {
                this.WriteVaryingAvailabilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteVaryingAvailabilitiesOperationCompleted);
            }
            this.InvokeAsync("WriteVaryingAvailabilities", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        vakanzen}, this.WriteVaryingAvailabilitiesOperationCompleted, userState);
        }
        
        private void OnWriteVaryingAvailabilitiesOperationCompleted(object arg) {
            if ((this.WriteVaryingAvailabilitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteVaryingAvailabilitiesCompleted(this, new WriteVaryingAvailabilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/WriteBookingFlag", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteBookingFlag(int knr, string pwd, int bid, int pmsvalue) {
            object[] results = this.Invoke("WriteBookingFlag", new object[] {
                        knr,
                        pwd,
                        bid,
                        pmsvalue});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteBookingFlagAsync(int knr, string pwd, int bid, int pmsvalue) {
            this.WriteBookingFlagAsync(knr, pwd, bid, pmsvalue, null);
        }
        
        /// <remarks/>
        public void WriteBookingFlagAsync(int knr, string pwd, int bid, int pmsvalue, object userState) {
            if ((this.WriteBookingFlagOperationCompleted == null)) {
                this.WriteBookingFlagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteBookingFlagOperationCompleted);
            }
            this.InvokeAsync("WriteBookingFlag", new object[] {
                        knr,
                        pwd,
                        bid,
                        pmsvalue}, this.WriteBookingFlagOperationCompleted, userState);
        }
        
        private void OnWriteBookingFlagOperationCompleted(object arg) {
            if ((this.WriteBookingFlagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteBookingFlagCompleted(this, new WriteBookingFlagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/WriteMinstay", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteMinstay(int knr, string pwd, int ztyp, string sdatum, string edatum, float minstay) {
            object[] results = this.Invoke("WriteMinstay", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        edatum,
                        minstay});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteMinstayAsync(int knr, string pwd, int ztyp, string sdatum, string edatum, float minstay) {
            this.WriteMinstayAsync(knr, pwd, ztyp, sdatum, edatum, minstay, null);
        }
        
        /// <remarks/>
        public void WriteMinstayAsync(int knr, string pwd, int ztyp, string sdatum, string edatum, float minstay, object userState) {
            if ((this.WriteMinstayOperationCompleted == null)) {
                this.WriteMinstayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteMinstayOperationCompleted);
            }
            this.InvokeAsync("WriteMinstay", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        edatum,
                        minstay}, this.WriteMinstayOperationCompleted, userState);
        }
        
        private void OnWriteMinstayOperationCompleted(object arg) {
            if ((this.WriteMinstayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteMinstayCompleted(this, new WriteMinstayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/WriteVaryingMinStays", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteVaryingMinStays(int knr, string pwd, int ztyp, string sdatum, int[] mindestNaechte) {
            object[] results = this.Invoke("WriteVaryingMinStays", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        mindestNaechte});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteVaryingMinStaysAsync(int knr, string pwd, int ztyp, string sdatum, int[] mindestNaechte) {
            this.WriteVaryingMinStaysAsync(knr, pwd, ztyp, sdatum, mindestNaechte, null);
        }
        
        /// <remarks/>
        public void WriteVaryingMinStaysAsync(int knr, string pwd, int ztyp, string sdatum, int[] mindestNaechte, object userState) {
            if ((this.WriteVaryingMinStaysOperationCompleted == null)) {
                this.WriteVaryingMinStaysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteVaryingMinStaysOperationCompleted);
            }
            this.InvokeAsync("WriteVaryingMinStays", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        mindestNaechte}, this.WriteVaryingMinStaysOperationCompleted, userState);
        }
        
        private void OnWriteVaryingMinStaysOperationCompleted(object arg) {
            if ((this.WriteVaryingMinStaysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteVaryingMinStaysCompleted(this, new WriteVaryingMinStaysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/WritePrices", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WritePrices(int knr, string pwd, int ztyp, string sdatum, string edatum, float preis) {
            object[] results = this.Invoke("WritePrices", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        edatum,
                        preis});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WritePricesAsync(int knr, string pwd, int ztyp, string sdatum, string edatum, float preis) {
            this.WritePricesAsync(knr, pwd, ztyp, sdatum, edatum, preis, null);
        }
        
        /// <remarks/>
        public void WritePricesAsync(int knr, string pwd, int ztyp, string sdatum, string edatum, float preis, object userState) {
            if ((this.WritePricesOperationCompleted == null)) {
                this.WritePricesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWritePricesOperationCompleted);
            }
            this.InvokeAsync("WritePrices", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        edatum,
                        preis}, this.WritePricesOperationCompleted, userState);
        }
        
        private void OnWritePricesOperationCompleted(object arg) {
            if ((this.WritePricesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WritePricesCompleted(this, new WritePricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/WriteVaryingPrices", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteVaryingPrices(int knr, string pwd, int ztyp, string sdatum, float[] preise) {
            object[] results = this.Invoke("WriteVaryingPrices", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        preise});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteVaryingPricesAsync(int knr, string pwd, int ztyp, string sdatum, float[] preise) {
            this.WriteVaryingPricesAsync(knr, pwd, ztyp, sdatum, preise, null);
        }
        
        /// <remarks/>
        public void WriteVaryingPricesAsync(int knr, string pwd, int ztyp, string sdatum, float[] preise, object userState) {
            if ((this.WriteVaryingPricesOperationCompleted == null)) {
                this.WriteVaryingPricesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteVaryingPricesOperationCompleted);
            }
            this.InvokeAsync("WriteVaryingPrices", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        preise}, this.WriteVaryingPricesOperationCompleted, userState);
        }
        
        private void OnWriteVaryingPricesOperationCompleted(object arg) {
            if ((this.WriteVaryingPricesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteVaryingPricesCompleted(this, new WriteVaryingPricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/WriteVaryingAvailabilitiesMinStaysPrices", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteVaryingAvailabilitiesMinStaysPrices(int knr, string pwd, int ztyp, string sdatum, int[] vakanzen, int[] mindestNaechte, float[] preise) {
            object[] results = this.Invoke("WriteVaryingAvailabilitiesMinStaysPrices", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        vakanzen,
                        mindestNaechte,
                        preise});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteVaryingAvailabilitiesMinStaysPricesAsync(int knr, string pwd, int ztyp, string sdatum, int[] vakanzen, int[] mindestNaechte, float[] preise) {
            this.WriteVaryingAvailabilitiesMinStaysPricesAsync(knr, pwd, ztyp, sdatum, vakanzen, mindestNaechte, preise, null);
        }
        
        /// <remarks/>
        public void WriteVaryingAvailabilitiesMinStaysPricesAsync(int knr, string pwd, int ztyp, string sdatum, int[] vakanzen, int[] mindestNaechte, float[] preise, object userState) {
            if ((this.WriteVaryingAvailabilitiesMinStaysPricesOperationCompleted == null)) {
                this.WriteVaryingAvailabilitiesMinStaysPricesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteVaryingAvailabilitiesMinStaysPricesOperationCompleted);
            }
            this.InvokeAsync("WriteVaryingAvailabilitiesMinStaysPrices", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        sdatum,
                        vakanzen,
                        mindestNaechte,
                        preise}, this.WriteVaryingAvailabilitiesMinStaysPricesOperationCompleted, userState);
        }
        
        private void OnWriteVaryingAvailabilitiesMinStaysPricesOperationCompleted(object arg) {
            if ((this.WriteVaryingAvailabilitiesMinStaysPricesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteVaryingAvailabilitiesMinStaysPricesCompleted(this, new WriteVaryingAvailabilitiesMinStaysPricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dirs21.de/WriteDefinedAvailabilitiesMinStaysPrices", RequestNamespace="http://www.dirs21.de/", ResponseNamespace="http://www.dirs21.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteDefinedAvailabilitiesMinStaysPrices(int knr, string pwd, int ztyp, DayRateDetail[] dayRateDetails) {
            object[] results = this.Invoke("WriteDefinedAvailabilitiesMinStaysPrices", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        dayRateDetails});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteDefinedAvailabilitiesMinStaysPricesAsync(int knr, string pwd, int ztyp, DayRateDetail[] dayRateDetails) {
            this.WriteDefinedAvailabilitiesMinStaysPricesAsync(knr, pwd, ztyp, dayRateDetails, null);
        }
        
        /// <remarks/>
        public void WriteDefinedAvailabilitiesMinStaysPricesAsync(int knr, string pwd, int ztyp, DayRateDetail[] dayRateDetails, object userState) {
            if ((this.WriteDefinedAvailabilitiesMinStaysPricesOperationCompleted == null)) {
                this.WriteDefinedAvailabilitiesMinStaysPricesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteDefinedAvailabilitiesMinStaysPricesOperationCompleted);
            }
            this.InvokeAsync("WriteDefinedAvailabilitiesMinStaysPrices", new object[] {
                        knr,
                        pwd,
                        ztyp,
                        dayRateDetails}, this.WriteDefinedAvailabilitiesMinStaysPricesOperationCompleted, userState);
        }
        
        private void OnWriteDefinedAvailabilitiesMinStaysPricesOperationCompleted(object arg) {
            if ((this.WriteDefinedAvailabilitiesMinStaysPricesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteDefinedAvailabilitiesMinStaysPricesCompleted(this, new WriteDefinedAvailabilitiesMinStaysPricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dirs21.de/")]
    public partial class DayRateDetail {
        
        private System.DateTime dateField;
        
        private float priceField;
        
        private int availableField;
        
        private int minNightsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public float Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int Available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
        
        /// <remarks/>
        public int MinNights {
            get {
                return this.minNightsField;
            }
            set {
                this.minNightsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadActiveRoomtypesCompletedEventHandler(object sender, ReadActiveRoomtypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadActiveRoomtypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadActiveRoomtypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadAvailabilitiesPricesMinstayCompletedEventHandler(object sender, ReadAvailabilitiesPricesMinstayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadAvailabilitiesPricesMinstayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadAvailabilitiesPricesMinstayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadBookingAddOnsCompletedEventHandler(object sender, ReadBookingAddOnsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadBookingAddOnsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadBookingAddOnsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadBookingdetailsCompletedEventHandler(object sender, ReadBookingdetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadBookingdetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadBookingdetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadBookingdetailsMergedCompletedEventHandler(object sender, ReadBookingdetailsMergedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadBookingdetailsMergedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadBookingdetailsMergedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadBookingsCompletedEventHandler(object sender, ReadBookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadBookingsPMSValueCompletedEventHandler(object sender, ReadBookingsPMSValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadBookingsPMSValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadBookingsPMSValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadBookingsPMSValueAndStatusCompletedEventHandler(object sender, ReadBookingsPMSValueAndStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadBookingsPMSValueAndStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadBookingsPMSValueAndStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadInactiveRoomtypesCompletedEventHandler(object sender, ReadInactiveRoomtypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadInactiveRoomtypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadInactiveRoomtypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadNotificationFaxnumberCompletedEventHandler(object sender, ReadNotificationFaxnumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadNotificationFaxnumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadNotificationFaxnumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WriteAvailabilitiesPricesMinstayCompletedEventHandler(object sender, WriteAvailabilitiesPricesMinstayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteAvailabilitiesPricesMinstayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteAvailabilitiesPricesMinstayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WriteAvailabilitiesCompletedEventHandler(object sender, WriteAvailabilitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteAvailabilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteAvailabilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WriteVaryingAvailabilitiesCompletedEventHandler(object sender, WriteVaryingAvailabilitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteVaryingAvailabilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteVaryingAvailabilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WriteBookingFlagCompletedEventHandler(object sender, WriteBookingFlagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteBookingFlagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteBookingFlagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WriteMinstayCompletedEventHandler(object sender, WriteMinstayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteMinstayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteMinstayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WriteVaryingMinStaysCompletedEventHandler(object sender, WriteVaryingMinStaysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteVaryingMinStaysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteVaryingMinStaysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WritePricesCompletedEventHandler(object sender, WritePricesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WritePricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WritePricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WriteVaryingPricesCompletedEventHandler(object sender, WriteVaryingPricesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteVaryingPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteVaryingPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WriteVaryingAvailabilitiesMinStaysPricesCompletedEventHandler(object sender, WriteVaryingAvailabilitiesMinStaysPricesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteVaryingAvailabilitiesMinStaysPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteVaryingAvailabilitiesMinStaysPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WriteDefinedAvailabilitiesMinStaysPricesCompletedEventHandler(object sender, WriteDefinedAvailabilitiesMinStaysPricesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteDefinedAvailabilitiesMinStaysPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteDefinedAvailabilitiesMinStaysPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591